INSERT INTO Companies (company_id, company_name, company_name_ruby, company_url, company_location, logo_image)
VALUES 
( 
    NULL,
    '学校法人麻生塾【麻生専門学校グループ】',
    'あそうじゅく',
    'https://recruit.asojuku.ac.jp/newgraduate/',
    '福岡県飯塚市芳雄町3-83',
    'aso.png'
),
(
    NULL,
    '富士ソフト株式会社',
    'ふじそふと',
    'https://www.fsi.co.jp/',
    '神奈川県横浜市中区桜木町1-1',
    'fji.png'
),
(
    NULL,
    'ＳＣＳＫ株式会社',
    'えすしーえすけい',
    'https://www.scsk.jp/',
    '東京都江東区豊洲3丁目2番20号',
    'scsk.png'
),
(
    NULL,
    '株式会社エヌ・ティ・ティエムイー',
    'えぬてぃてぃえむいー',
    'https://www.ntt-me.co.jp/',
    '東京都豊島区東池袋3-21-14',
    'ntt.png'
),
(
    NULL,
    '株式会社アウトソーシングテクノロジー',
    'あうとそーしんぐてくのろじー',
    'https://www.ostechnology.co.jp/',
    '東京都千代田区丸の内1丁目8番3号',
    'out.png'
),
(
    NULL,
    'ヤフー株式会社',
    'やふー',
    'https://about.yahoo.co.jp/',
    '東京都千代田区紀尾井町1番3号',
    'yahoo.png'
),
( 
    NULL,
    'NEC株式会社',
    'ねっく',
    'https://jpn.nec.com/index.html',
    '東京都港区芝5-7-1',
    'nec.png'
),
(
    NULL,
    '日本コンピューター株式会社',
    'にほんこんぴゅーたー',
    'https://www.nck.co.jp/',
    '福岡県北九州市小倉北区鍛冶町2丁目4番1号',
    'nihon.png'
),
(
    NULL,
    '株式会社リクルートホールディングス',
    'りくるーとほーるでぃんくす',
    'https://recruit-holdings.com/ja/',
    '東京都千代田区丸の内1丁目9−2',
    'recruit.png'
),
(
    NULL,
    '株式会社日立製作所',
    'ひたちせいさくじょ',
    'https://www.hitachi.co.jp/',
    '東京都千代田区丸の内一丁目6番6号',
    'hitachi.png'
),
(
    NULL,
    'テクノブレイブ株式会社',
    'てくのぶれいぶ',
    'https://www.tbrave.com/',
    '東京都千代田区内神田1丁目2番8号楠本第2ビル2階',
    'techno.png'
),
(
    NULL,
    'ワールドビジネスセンター株式会社',
    'わーるどびじねすせんたー',
    'https://www.wbc.co.jp/',
    '京都府京都市南区西九条東御幸田町25番2',
    'wbc.png'
),
(
    NULL,
    '株式会社ミライト・ワン・システムズ',
    'みらいとわんしすてむず',
    'https://www.mirait-one-systems.co.jp/',
    '東京都港区東新橋2丁目3番3号',
    'mirait.png'
),
(
    NULL,
    '木村情報技術株式会社',
    'きむらじょうほうぎじゅつ',
    'https://www.k-idea.jp/',
    '佐賀県佐賀市卸本町6番1号',
    'kimura.png'
),
(
    NULL,
    'ＪＴＰ株式会社',
    '日本サード・パーティ',
    'https://www.jtp.co.jp/',
    '東京都品川区北品川4丁目7番35号',
    'jtp.png'
);

INSERT INTO Companies (company_id, company_name, company_name_ruby, company_url, company_location, logo_image)
VALUES 
(
    NULL, 
    '株式会社アクセンチュア', 
    'あくせんちゅあ', 
    'https://www.accenture.com/jp-ja', 
    '東京都港区赤坂1-8-1 赤坂インターシティAIR（受付: 8階）', 
    'accenture.png' 
),
(
    NULL, 
    '株式会社アドウェイズ', 
    'あどうぇいず', 
    'https://www.adways.net/', 
    '東京都新宿区西新宿五丁目一番一号 住友不動産新宿ファーストタワー5階  ', 
    'adways.png' 
),
(
    NULL, 
    '株式会社アマゾンジャパン', 
    'あまぞんじゃぱん', 
    'https://www.amazon.co.jp/', 
    '東京都目黒区下目黒1-8-1 アルコタワーアネックス', 
    'amazonjapan.png' 
),
(
    NULL, 
    '株式会社イー・ガーディアン', 
    'いーがーでぃあん', 
    'https://www.e-guardian.co.jp/', 
    '東京都港区虎ノ門1-2-8 虎ノ門琴平タワー8F', 
    'eguardian.png' 
),
(
    NULL, 
    '株式会社インターネットイニシアティブ', 
    'いんたーねっといにしあてぃぶ', 
    'https://www.iij.ad.jp/', 
    '東京都千代田区富士見2-10-2', 
    'iij.png' 
),
(
    NULL, 
    '株式会社ウィルゲート', 
    'うぃるげーと', 
    'https://www.willgate.co.jp/', 
    '東京都港区南青山3-8-38 クローバー南青山3F', 
    'willgate.png' 
),
(
    NULL, 
    '株式会社ウフル', 
    'うふる', 
    'https://uhuru.co.jp/', 
    '東京都港区虎ノ門4-1-1神谷町トラストタワー23階 WeWork内', 
    'uhuru.png' 
),
(
    NULL, 
    'イーベイジャパン株式会社', 
    'いーべいじゃぱん', 
    'https://www.ebay.co.jp', 
    '東京都渋谷区南平台町16-28 グラスシティ6F', 
    'ebay.png' 
),
(
    NULL, 
    'インテル株式会社', 
    'いんてる', 
    'https://www.intel.co.jp', 
    '東京都千代田区丸の内 3-1-1 国際ビル 5 階', 
    'intel.png' 
),
(
    NULL, 
    'インフォコム株式会社', 
    'いんふぉこむ', 
    'https://www.infocom.co.jp', 
    '東京都港区赤坂9-7-2 ミッドタウン・イースト10階', 
    'infocom.png' 
),
(
    NULL, 
    'インフォメーション・ディベロプメント株式会社', 
    'いんふぉめーしょん・でぃべろぷめんと', 
    'https://www.idnet.co.jp', 
    '東京都千代田区五番町12-1 番町会館', 
    'idnet.png' 
),
(
    NULL, 
    '株式会社ウイングアーク1st', 
    'ういんぐあーくふぁーすと', 
    'https://www.wingarc.com/', 
    '東京都港区六本木三丁目2番1号 六本木グランドタワー', 
    'wingarc.png' 
),
(
    NULL, 
    '株式会社ウィルソン・ラーニング ワールドワイド', 
    'うぃるそん・らーにんぐわ・ーるどうぃど', 
    'https://www.wilsonlearning.com/jp/', 
    '東京都港区虎ノ門2-10-1虎ノ門ツインビルディング 東棟13階', 
    'wilsonlearning.png' 
),
(
    NULL, 
    '株式会社ウィズテクノロジー', 
    'うぃずてくのろじー', 
    'https://www.whizz-tech.co.jp/', 
    '大阪府大阪市西区江戸堀2-1-1 江戸堀センタービルB1F', 
    'withtechnology.png' 
),
(
    NULL, 
    '株式会社ウルシステムズ', 
    'うるしすてむず', 
    'https://www.ulsystems.co.jp/', 
    '東京都中央区晴海 1-8-10 トリトンスクエア タワーX 14階', 
    'ulsystems.png' 
),
(
    NULL, 
    'エクサ株式会社', 
    'えくさ', 
    'https://www.exa-corp.co.jp/', 
    '神奈川県横浜市西区みなとみらい4-4-5 横浜アイマークプレイス2階', 
    'exa.png' 
),
(
    NULL, 
    'エヌ・ティ・ティ・データ先端技術株式会社', 
    'えぬ・てぃ・てぃ・でーたせんたんぎじゅつ', 
    'https://www.intellilink.co.jp/home.aspx', 
    '東京都中央区月島1-15-7 パシフィックマークス月島', 
    'nttd-ati.png' 
),
(
    NULL, 
    '株式会社エヌ・エス・ティ', 
    'えぬ・えす・てぃ', 
    'https://www.cae-nst.co.jp/', 
    '東京都文京区小石川 4-20-3 ベルスクエア小石川 4F', 
    'nst.png' 
),
(
    NULL, 
    'エムオーテックス株式会社', 
    'えむおーてっくす', 
    'https://www.motex.co.jp/', 
    '大阪市淀川区西中島5-12-12 エムオーテックス新大阪ビル', 
    'motex.png' 
),
(
    NULL, 
    'エムスリー株式会社', 
    'えむすりー', 
    'https://corporate.m3.com/', 
    '東京都港区赤坂1丁目11番44号 赤坂インターシティ10階', 
    'm3.png' 
),
(
    NULL, 
    '株式会社オプティム', 
    'おぷてぃむ', 
    'https://www.optim.co.jp/', 
    '東京都港区海岸1丁目2番20号 汐留ビルディング 18F', 
    'optim.png' 
),
(
    NULL, 
    '株式会社オービック', 
    'おーびっく', 
    'https://www.obic.co.jp/', 
    '東京都中央区京橋2丁目4番15号', 
    'obic.png' 
),
(
    NULL, 
    'オムロン株式会社', 
    'おむろん', 
    'https://www.omron.co.jp/', 
    '京都市下京区塩小路通堀川東入', 
    'omron.png' 
),
(
    NULL, 
    'オラクル株式会社', 
    'おらくる', 
    'https://www.oracle.com/jp/', 
    '東京都港区北青山2-5-8 オラクル青山センター', 
    'oracle.png' 
),
(
    NULL, 
    '株式会社オージス総研', 
    'おーじすそうけん', 
    'https://www.ogis-ri.co.jp/', 
    '大阪市西区千代崎3丁目南2番37号', 
    'ogis.png' 
),
(
    NULL, 
    '株式会社オウケイウェイヴ', 
    'おうけいうぇいゔ', 
    'https://www.okwave.co.jp/', 
    '東京都港区新橋3丁目11-8 オーイズミ新橋第2ビル702', 
    'okwave.png' 
),
(
    NULL, 
    'オリックス株式会社', 
    'おりっくす', 
    'https://www.orix.co.jp/', 
    '東京都港区浜松町二丁目4番1号 世界貿易センタービル南館', 
    'orix.png' 
),
(
    NULL, 
    '株式会社カカクコム', 
    'かかくこむ', 
    'https://corporate.kakaku.com/', 
    '東京都渋谷区恵比寿南3丁目5番7号 デジタルゲートビル', 
    'kakaku.png' 
),
(
    NULL, 
    '株式会社カヤック', 
    'かやっく', 
    'https://www.kayac.com/', 
    '神奈川県鎌倉市御成町11-8', 
    'kayac.png' 
),
(
    NULL, 
    '株式会社カプコン', 
    'かぷこん', 
    'https://www.capcom.co.jp/', 
    '大阪市中央区内平野町三丁目1番3号', 
    'capcom.png' 
),
(
    NULL, 
    '株式会社カイロスマーケティング', 
    'かいろすまーけてぃんぐ', 
    'https://www.kairosmarketing.net/', 
    '東京都渋⾕区神宮前2-34-17 住友不動産原宿ビル 17F', 
    'kairos.png' 
),
(
    NULL, 
    'カイテク株式会社', 
    'かいてく', 
    'https://corp.caitech.co.jp/', 
    '東京都渋谷区神宮前5丁目53-67 コスモス青山SOUTH棟507', 
    'kaitek.png' 
),
(
    NULL, 
    '株式会社キカガク', 
    'きかがく', 
    'https://kikagaku.co.jp/', 
    '東京都渋谷区渋谷2-6-4 渋谷イーストプレイス4F', 
    'kikagaku.png' 
),
(
    NULL, 
    '株式会社キノトロープ', 
    'きのとろーぷ', 
    'https://www.kinotrope.co.jp/', 
    '東京都渋谷区大山町45-14', 
    'kinotrope.png' 
),
(
    NULL, 
    '株式会社キューブシステム', 
    'きゅーぶしすてむ', 
    'https://www.cubesystem.co.jp/', 
    '東京都品川区大崎2-11-1 大崎ウィズタワー', 
    'cubesystem.png' 
),
(
    NULL, 
    '株式会社キューブ・ソフト', 
    'きゅーぶそふと', 
    'https://www.cube-soft.jp/', 
    '大阪府豊中市待兼山町21-9 山吉ビル402号
', 
    'cubesoft.png' 
),
(
    NULL, 
    '株式会社キッズウェイ', 
    'きっずうぇい', 
    'https://www.kids-way.ne.jp/index.html', 
    '愛知県瀬戸市山の田町155番地', 
    'kidsway.png' 
),
(
    NULL, 
    '株式会社クレスコ', 
    'くれすこ', 
    'https://www.cresco.co.jp/', 
    '東京都港区港南2-15-1 品川インターシティA棟 25階～27階', 
    'cresco.png' 
),
(
    NULL, 
    '株式会社クリーク・アンド・リバー社', 
    'くりーくあんどりばーしゃ', 
    'https://www.cri.co.jp/', 
    '東京都港区新橋四丁目1番1号新虎通りCORE', 
    'cri.png' 
),
(
    NULL, 
    '株式会社クライム', 
    'くらいむ', 
    'https://www.climb-net.co.jp/', 
    '群馬県前橋市表町2-30-8アクエル前橋4階', 
    'climb.png' 
),
(
    NULL, 
    '株式会社クリエーションライン', 
    'くりえーしょんらいん', 
    'https://www.creationline.com/', 
    '東京都千代田区神田佐久間町3-6', 
    'creationline.png' 
),
(
    NULL, 
    '株式会社クラウドワークス', 
    'くらうどわーくす', 
    'https://crowdworks.co.jp/', 
    '東京都渋谷区恵比寿4-20-3 恵比寿ガーデンプレイスタワー6階', 
    'crowdworks.png' 
),
(
    NULL, 
    '株式会社クラフトマンソフトウェア', 
    'くらふとまんそふとうぇあ', 
    'https://craftsman-software.com/', 
    '東京都板橋区赤塚8-10-2-701', 
    'craftsmansoftware.png' 
),
(
    NULL, 
    '株式会社クレディセゾン', 
    'くれでぃせぞん', 
    'https://www.saisoncard.co.jp/', 
    '東京都豊島区東池袋3-1-1 サンシャイン60・52F', 
    'saison.png' 
),
(
    NULL, 
    '株式会社ケーズデンキ', 
    'けーずでんき', 
    'https://www.ksdenki.co.jp/kshd/default.aspx', 
    '茨城県水戸市城南二丁目7番5号', 
    'kenz.png' 
), 
(
    NULL, 
    '株式会社ケイ・エス・テクノロジー', 
    'けい・えす・てくのろじー', 
    'https://ks-tec.co.jp/', 
    '東京都中央区日本橋蛎殻町1-38-12 油商会館ビル3階', 
    'kei_es.png' 
),
(
    NULL, 
    'エスティケイテクノロジー株式会社', 
    'えすけいてくのろじー', 
    'https://www.stk-net.co.jp/', 
    '大分県大分市大字三佐2468番地10 ', 
    'kei_technology.png' 
),
(
    NULL, 
    '株式会社ケイ・システム', 
    'けい・しすてむ', 
    'https://www.kei-system.com/', 
    '東京都渋谷区神泉町11-10', 
    'k_system.png' 
),
(
    NULL, 
    '株式会社ケープロジェクト', 
    'けーぷろじぇくと', 
    'https://www.kproject.co.jp/', 
    '東京都千代田区外神田3-14-3 福栄秋葉原ビル8階', 
    'kei_pro.png' 
), 
(
    NULL, 
    '株式会社コニカミノルタ', 
    'こにかみのるた', 
    'https://www.konicaminolta.com/jp-ja/index.html', 
    '東京都千代田区丸の内2-7-2 JPタワー', 
    'conikami.png' 
),
(
    NULL, 
    '株式会社レスター', 
    'れすたー', 
    'https://www.restargp.com/', 
    '東京都港区港南二丁目10番9号 レスタービルディング', 
    'resuta.png' 
),
(
    NULL, 
    '株式会社コラボシステムズ', 
    'こらぼしすてむず', 
    'https://www.c-sys.co.jp/', 
    '東京都練馬区下石神井1-2-3-201', 
    'collabo_systems.png' 
),
(
    NULL, 
    'コムチュア株式会社', 
    'こむちゅあ', 
    'https://www.comture.com/', 
    '東京都品川区大崎1-11-2 ゲートシティ大崎イーストタワー9F・15F', 
    'com.png' 
),
(
    NULL, 
    '株式会社コア', 
    'こあ', 
    'https://www.core.co.jp/', 
    '東京都世田谷区三軒茶屋1丁目22番3号', 
    'core.png' 
),
(
    NULL, 
    '株式会社サイバーエージェント', 
    'さいばーえーじぇんと', 
    'https://www.cyberagent.co.jp/', 
    '東京都渋谷区宇田川町40番1号 Abema Towers', 
    'CyberAgent.png' 
),
(
    NULL, 
    'サイボウズ株式会社', 
    'さいぼうず', 
    'https://cybozu.co.jp/', 
    ' 東京都中央区日本橋2-7-1 東京日本橋タワー 27階', 
    'Cybozu.png' 
),
(
    NULL, 
    'サン電子株式会社', 
    'さんでんし', 
    'https://www.sun-denshi.co.jp/', 
    '名古屋市中村区名駅四丁目2番25号 名古屋ビルディング桜館２階', 
    'sun.png' 
),
(
    NULL, 
    '株式会社サーバーワークス', 
    'さいばーわーくす', 
    'https://www.serverworks.co.jp/', 
    '東京都新宿区揚場町1番21号 飯田橋升本ビル2階', 
    'Serverworks.png' 
),
(
    NULL, 
    '株式会社サムライズ', 
    'さむらいず', 
    'https://www.samuraiz.co.jp/', 
    '東京都品川区大崎1-6-4 新大崎勧業ビル5F', 
    'Samurize.png' 
),
(
    NULL, 
    'シスコシステムズ合同会社', 
    'しすこしすてむず', 
    'https://www.cisco.com/site/jp/ja/index.html', 
    '東京都港区赤坂9-7-1ミッドタウン・タワー', 
    'Cisco Systems.png' 
),
(
    NULL, 
    '株式会社システムズエンジニアリング', 
    'しすてむずえんじにありんぐ', 
    'https://www.systems-eng.co.jp/', 
    '東京都文京区小石川1-4-12 文京ガーデンザウエスト801', 
    'Systems Engineering.png' 
),
(
    NULL, 
    'シンクレイヤ株式会社', 
    'しんくれいあ', 
    'https://www.synclayer.co.jp/#TOP', 
    '名古屋市中区千代⽥⼆丁⽬21番18号', 
    'Synclayer.png' 
),
(
    NULL, 
    '株式会社システナ', 
    'しすてな', 
    'https://www.systena.co.jp/', 
    '東京都港区海岸1丁目2番20号 汐留ビルディング 14F・16F', 
    'Systena Corporation.png' 
),
(
    NULL, 
    'Sky株式会社', 
    'すかい', 
    'https://www.skygroup.jp/', 
    '東京都港区港南2丁目18番1号 JR品川イーストビル 9階', 
    'Sky.png' 
),
(
    NULL, 
    'スリーエムジャパン株式会社', 
    'すりーえむじゃぱん', 
    'https://www.3mcompany.jp/3M/ja_JP/company-jp/', 
    '東京都品川区北品川6-7-29', 
    '3M Japan .png' 
),
(
    NULL, 
    'SCSK株式会社', 
    'えすしーえすけー', 
    'https://www.scsk.jp/', 
    '東京都江東区豊洲3-2-20 豊洲フロント', 
    'SCSK.png' 
),

(
    NULL, 
    'スターティアホールディングス株式会社', 
    'すたーてぃあほーるでぃんぐす', 
    'https://www.startiaholdings.com/', 
    '東京都新宿区西新宿2-3-1 新宿モノリス19階', 
    'Startia.png' 
),
(
    NULL, 
    'セガサミーホールディングス株式会社', 
    'せがさみーほーるでぃんぐす', 
    'https://www.segasammy.co.jp/ja/', 
    '東京都品川区西品川一丁目1-1 住友不動産大崎ガーデンタワー', 
    'Sega Sammy.png' 
),
(
    NULL, 
    'セコム株式会社', 
    'せこむ', 
    'https://www.secom.co.jp/', 
    '東京都渋谷区神宮前1丁目5番1号', 
    'Secom.png' 
),
(
    NULL, 
    '株式会社セラク', 
    'せらく', 
    'https://www.seraku.co.jp/', 
    '東京都新宿区西新宿7-5-25 西新宿プライムスクエア 6F', 
    'Seraku.png' 
),
(
    NULL, 
    '株式会社セゾンテクノロジー', 
    'せぞんてくのろじー', 
    'https://www.saison-technology.com/', 
    '東京都港区赤坂1-8-1 赤坂インターシティAIR 19F', 
    'Saison Information.png' 
),
(
    NULL, 
    '株式会社セプテーニ・ホールディングス', 
    'せぷてーに・ほーるでぃんぐす', 
    'https://www.septeni-holdings.co.jp/', 
    '東京都新宿区西新宿8丁目17番1号 住友不動産新宿グランドタワー30F',
    'Septeni.png' 
),
(
    NULL, 
    'セーフィー株式会社', 
    'せーふぃー', 
    'https://safie.co.jp/', 
    '東京都品川区西品川1-1-1 住友不動産大崎ガーデンタワー', 
    'Safie.png' 
),
(
    NULL, 
    'ソフトバンク株式会社', 
    'そふとばんく', 
    'https://www.softbank.jp/', 
    '東京都港区海岸一丁目7番1号', 
    'SoftBank.png' 
),
(
    NULL, 
    'ソニー株式会社', 
    'そにー', 
    'https://www.sony.co.jp/', 
    'ソニー株式会社', 
    'Sony.png' 
),
(
    NULL, 
    '株式会社ソフトウェア・サービス', 
    'そふとうぇあ・さーびす', 
    'https://www.softs.co.jp/', 
    '大阪府大阪市淀川区西宮原2丁目6番1号', 
    'Software.png' 
),
(
    NULL, 
    '株式会社ソリトンシステムズ', 
    'そりとんしすてむず', 
    'https://www.soliton.co.jp/', 
    '東京都新宿区新宿 2-4-3', 
    'Soliton.png' 
),
(
    NULL, 
    '株式会社ソフトフロントホールディングス', 
    'そふとふろんとほーるでぃんぐす', 
    'https://www.softfront.co.jp/', 
    '東京都千代田区九段南一丁目4番5号 泉九段ビル 6F', 
    'Softfront.png' 
),
(
    NULL, 
    '株式会社ソリューション・アンド・テクノロジー', 
    'そりゅーしょん・あんど・てくのろじー', 
    'https://www.solty.co.jp/', 
    '東京都千代田区四番町６番  東急番町ビル８階', 
    'Solution.png' 
),
(
    NULL, 
    '株式会社ソフィアホールディングス', 
    'そふぃあほーるでぃんぐす', 
    'https://www.sophia.com/', 
    '神奈川県横浜市港北区新横浜2丁目15番12号 共立新横浜ビル5階', 
    'Sophia.png' 
),
(
    NULL, 
    '株式会社タップ', 
    'たっぷ', 
    'https://www.tap-ic.co.jp/about/', 
    '東京都江東区東陽2-2-4 マニュライフプレイス東陽町1F', 
    'TAPP.png' 
),
(
    NULL, 
    'タビィコム株式会社', 
    'たびぃこむ', 
    'https://tavii.co.jp/', 
    '東京都中央区日本橋茅場町2-17-13 第2井上ビル 403', 
    'tavii.png' 
),
(
    NULL, 
    'タワーシステムズ株式会社', 
    'たわーしすてむず', 
    'https://towersystems.co.jp/', 
    '東京都千代田区九段北 1-10-5 サンブリッジ九段ビル8階', 
    'towersystem.png' 
),
(
    NULL, 
    'タブレットジャパン株式会社', 
    'たぶれっとじゃぱん', 
    'https://www.tabletjapan.jp/', 
    '東京都港区三田1-6-7 WATANABEビル2F D4DR内', 
    'tablet.png' 
),
(
    NULL, 
    'チームラボ株式会社', 
    'ちーむらぼ', 
    'https://www.team-lab.com/', 
    '東京都千代田区神田小川町2-12 小川町進興受付ビル', 
    'teamlab.png' 
),
(
    NULL, 
    'チエル株式会社', 
    'ちえる', 
    'https://www.chieru.co.jp/', 
    '東京都品川区東品川2-2-24 天王洲セントラルタワー22F', 
    'chieru.png' 
),
(
    NULL, 
    '株式会社チームスピリット', 
    'ちーむすぴりっと', 
    'https://corp.teamspirit.com/ja-jp/', 
    '東京都千代田区内幸町2-1-6 日比谷パークフロント19F', 
    'teamspirit.png' 
),
(
    NULL, 
    '株式会社チップワンストップ', 
    'ちーむわんすとっぷ', 
    'https://www.chip1stop.com/about/', 
    '神奈川県横浜市港北区新横浜三丁目19番1号LIVMOライジングビル10階', 
    'chip1stop.png' 
),
(
    NULL, 
    '株式会社ツクルバ', 
    'つくるば', 
    'https://tsukuruba.com/', 
    '東京都渋谷区恵比寿4-3-14 恵比寿SSビル 7F', 
    'tsukuruba.png' 
),
(
    NULL, 
    'ツバイソ株式会社', 
    'つばいそ', 
    'https://tsubaiso.jp/', 
    '東京都渋谷区幡ヶ谷2-6-5 梅村ビル幡ヶ谷6階', 
    'tsubaiso.png' 
),
(
    NULL, 
    '株式会社ツリーベル', 
    'つりーべる', 
    'https://www.treebell.co.jp/', 
    '東京都新宿区四谷坂町9番6号 坂町Mビル', 
    'treebell.png' 
),
(
    NULL, 
    '株式会社ツナグ・ソリューションズ', 
    'つなぐ・そりゅーしょんず', 
    'https://tghd.co.jp/', 
    '東京都中央区銀座7-3-5 ヒューリック銀座7丁目ビル7・8階', 
    'tghd.png' 
),
(
    NULL, 
    '株式会社ツルカメ', 
    'つるかめ', 
    'https://turucame.jp/', 
    '東京都世田谷区太子堂4-28-11 川金ビル202', 
    'turucame.png' 
),
(
    NULL, 
    'テクマトリックス株式会社', 
    'てくまとりっくす', 
    'https://www.techmatrix.co.jp/index.html', 
    '東京都港区港南1-2-70 品川シーズンテラス 24F', 
    'techmatrix.png' 
),
(
    NULL, 
    '株式会社テラスカイ', 
    'てらすかい', 
    'https://www.terrasky.co.jp/', 
    '東京都中央区日本橋二丁目11番2号 太陽生命日本橋ビル 15～17階 ', 
    'terrasky.png' 
),
(
    NULL, 
    'テックファーム株式会社', 
    'てっくふぁーむ', 
    'https://www.techfirm.co.jp/', 
    '東京都新宿区西新宿3丁目20番2号 東京オペラシティタワー23F', 
    'techfirm.png' 
),
(
    NULL, 
    'テクノプロ・ホールディングス株式会社', 
    'てくのぷろ・ほーるでぃんぐす', 
    'https://www.technoproholdings.com/', 
    '東京都港区六本木6-10-1 六本木ヒルズ森タワー35階', 
    'technoproholdings.png' 
),
(
    NULL, 
    '株式会社テイジイエル', 
    'ていじいえる', 
    'https://tgl.co.jp/', 
    '大阪市中央区城見1丁目3番7号 松下IMPビル', 
    'tgl.png' 
),
(
    NULL, 
    '株式会社テクノスジャパン', 
    'てくのすじゃぱん', 
    'https://www.tecnos.co.jp/', 
    '東京都新宿区西新宿3-20-2東京オペラシティタワー14階', 
    'tecnos.png' 
),
(
    NULL, 
    '株式会社テプコシステムズ', 
    'てぷこしすてむず', 
    'https://www.tepsys.co.jp/', 
    '東京都江東区永代2丁目37番28号 澁澤シティプレイス永代', 
    'tepsys.png' 
),
(
    NULL, 
    'Terra Drone株式会社', 
    'てらどろーん', 
    'https://terra-drone.net/', 
    '東京都渋谷区渋谷2丁目12-19東建インターナショナルビル３階', 
    'terra-drone.png' 
),
(
    NULL, 
    '株式会社トヨタシステムズ', 
    'とよたしすてむず', 
    'https://www.toyotasystems.com/', 
    '名古屋市中村区名駅1-1-1 JPタワー名古屋32F', 
    'toyotasystems.png' 
),
(
    NULL, 
    '東芝デジタルソリューションズ株式会社', 
    'とうしばでじたるそりゅーしょんず', 
    'https://www.global.toshiba/jp/company/digitalsolution.html', 
    '神奈川県川崎市幸区堀川町72番地34', 
    'toshiba.png' 
),
(
    NULL, 
    'トランスコスモス株式会社', 
    'とらんすこすもす', 
    'https://www.trans-cosmos.co.jp/', 
    '東京都豊島区東池袋3-1-1 サンシャイン60', 
    'trans-cosmos.png' 
),
(
    NULL, 
    '株式会社ドワンゴ', 
    'どわんご', 
    'https://dwango.co.jp/', 
    '東京都中央区銀座4-12-15 歌舞伎座タワー', 
    'dwango.png' 
),
(
    NULL, 
    'トランスウェア株式会社', 
    'とらんすうぇあ', 
    'https://www.trans-ware.co.jp/', 
    '東京都港区新橋3-2-5 5東洋海事ビル6階', 
    'trans-ware.png' 
),
(
    NULL, 
    'トレンドマイクロ株式会社', 
    'とれんどまいくろ', 
    'https://www.trendmicro.com/ja_jp/business.html', 
    '東京都新宿区新宿4-1-6 JR新宿ミライナタワー', 
    'trendmicro.png' 
),
(
    NULL, 
    '株式会社トリプルアイズ', 
    'とりぷるあいず', 
    'https://www.3-ize.jp/', 
    '東京都千代田区神田駿河台三丁目４番地 龍名館本店ビルディング１２階', 
    '3-ize.png' 
),
(
    NULL, 
    '株式会社ドリーム・アーツ', 
    'どりーむ・あーつ', 
    'https://www.dreamarts.co.jp/', 
    '東京都渋谷区恵比寿4-20-3 恵比寿ガーデンプレイスタワー29F', 
    'dreamarts.png' 
),
(
    NULL, 
    'トビラシステムズ株式会社', 
    'とびらしすてむず', 
    'https://tobila.com/', 
    '東京都千代田区神田駿河台2-3-6 CIRCLES御茶ノ水 10F', 
    'tobila.png' 
),
(
    NULL, 
    '株式会社ナビタイムジャパン', 
    'なびたいむ', 
    'https://corporate.navitime.co.jp/', 
    '東京都港区南青山3-8-38', 
    'navitime.png' 
),
(
    NULL, 
    '株式会社ナカヨ', 
    'なかよ', 
    'https://www.nyc.co.jp/', 
    '群馬県前橋市総社町一丁目3番2号 ', 
    'nyc.png' 
),
(
    NULL, 
    '株式会社ナノオプト・メディア', 
    'なのおぷと・めでぃあ', 
    'https://nanooptmedia.jp/', 
    '東京都新宿区新宿1-12-5 Uni-works新宿御苑3階', 
    'nanooptmedia.png' 
),
(
    NULL, 
    '株式会社NAVIS', 
    'なびす', 
    'https://navis-co.jp/', 
    '東京都港区赤坂2-11-13COMMON Akasaka 6F', 
    'navis.png' 
),
(
    NULL, 
    'ナレッジワークス株式会社', 
    'なれっじわーくす', 
    'https://hp.knowledge-works.co.jp/', 
    '東京都港区芝公園2-11-1 住友不動産 芝公園タワー22階', 
    'knowledge.png' 
),
(
    NULL, 
    '株式会社ナチュラリープラス', 
    'なちゅらりーぷらす', 
    'https://www.naturally-plus.com/jp/ja/', 
    '東京都港区六本木1-6-1 泉ガーデンタワー35階', 
    'naturally.png' 
),
(
    NULL, 
    '日本電気株式会社', 
    'にほんでんき', 
    'https://jpn.nec.com/index.html', 
    '東京都港区芝五丁目7番1号', 
    'nec.png' 
),
(
    NULL, 
    '日本アイ・ビー・エム株式会社', 
    'にほんあい・びー・えむ', 
    'https://www.ibm.com/jp-ja', 
    '東京都港区虎ノ門二丁目6番1号 虎ノ門ヒルズ ステーションタワー', 
    'ibm.png' 
),
(
    NULL, 
    '日本オラクル株式会社', 
    'にほんおらくる', 
    'https://www.oracle.com/jp/', 
    '東京都港区北青山二丁目5-8オラクル青山センター', 
    'oraclejp.png' 
),
(
    NULL, 
    '日本マイクロソフト株式会社 ', 
    'にほんまいくろそふと', 
    'https://www.microsoft.com/ja-jp/mscorp', 
    '東京都港区港南 2-16-3 品川グランドセントラルタワー', 
    'microsoft.png' 
),
(
    NULL, 
    '日本システム技術株式会社', 
    'にほんしすてむぎじゅつ', 
    'https://www.jast.jp/', 
    '東京都港区港南二丁目16番2号（太陽生命品川ビル27階）', 
    'jast.png' 
),
(
    NULL, 
    '日本電信電話株式会社', 
    'にほんでんしんでんわ', 
    'https://group.ntt/jp/', 
    '東京都千代田区大手町一丁目5番1号 大手町ファーストスクエア イーストタワー', 
    'ntt.png' 
),
(
    NULL, 
    '株式会社ヌーラボ', 
    'ぬーらぼ', 
    'https://nulab.com/ja/', 
    '福岡県福岡市中央区大名一丁目8-6 HCC BLD.', 
    'nulab.png' 
),
(
    NULL, 
    '有限会社ぬくもり工房', 
    'ぬくもりこうぼう', 
    'https://nukumorikoubou.com/', 
    '静岡県浜松市浜名区染地台3-12-25', 
    'nukumori.png' 
),
(
    NULL, 
    '株式会社ネクソン', 
    'ねくそん', 
    'https://www.nexon.co.jp/', 
    '東京都港区六本木1丁目4番5号', 
    'nexon.png' 
),
(
    NULL, 
    '株式会社ネクスト ', 
    'ねくすと', 
    'https://www.nextinc.co.jp/', 
    '東京都品川区南品川2-15-10', 
    'nextinc.png' 
),
(
    NULL, 
    '株式会社ネクステージ', 
    'ねくすてーじ', 
    'https://www.nextage.jp/', 
    '愛知県名古屋市中区新栄町一丁目1番地 明治安田生命名古屋ビル14階', 
    'nextage.png' 
),
(
    NULL, 
    '株式会社ネオキャリア', 
    'ねおきゃりあ', 
    'https://www.neo-career.co.jp/', 
    '東京都新宿区西新宿1-22-2 新宿サンエービル 2階', 
    'neo-career.png' 
),
(
    NULL, 
    '株式会社ネクスティ エレクトロニクス', 
    'ねくすてぃ・えれくとろにくす', 
    'https://www.nexty-ele.com/', 
    '東京都港区港南2-3-13 品川フロントビル', 
    'nexty-ele.png' 
),
(
    NULL, 
    '株式会社ネオス', 
    'ねおす', 
    'https://www.neos.co.jp/', 
    '神戸市中央区加納町6丁目2番1号', 
    'neos.png' 
),
(
    NULL, 
    '株式会社ネオジャパン', 
    'ねおじゃぱん', 
    'https://www.neo.co.jp/', 
    '神奈川県横浜市西区みなとみらい二丁目2-1', 
    'neo.png' 
),
(
    NULL, 
    'ネクストウェア株式会社', 
    'ねくすとうぇあ', 
    'https://www.nextware.co.jp/', 
    '大阪府大阪市中央区北久宝寺町 4-3-11ネクストウェアビル', 
    'nextware.png' 
),
(
    NULL, 
    'ネスレ日本株式会社', 
    'ねすれ',
    'https://www.nestle.co.jp/', 
    '神戸市中央区御幸通７-1-１５ネスレハウス', 
    'nestle.png' 
),
(
    NULL, 
    '株式会社ネオマーケティング', 
    'ねおまーけてぃんぐ', 
    'https://neo-m.jp/', 
    '東京都渋谷区南平台町16-25 養命酒ビル11F', 
    'neo-m.png' 
),
(
    NULL, 
    '野村ホールディングス株式会社', 
    'のむらほーるでぃんぐす', 
    'https://www.nomuraholdings.com/jp/top.html', 
    '東京都中央区日本橋1-13-1', 
    'nomuraholdings.png' 
),
(
    NULL, 
    '株式会社ノリタケカンパニーリミテド', 
    'のりたけかんぱにーりみてど', 
    'https://noritake.co.jp/', 
    '愛知県名古屋市西区則武新町三丁目1番36号', 
    'noritake.png' 
),
(
    NULL, 
    '野村不動産ホールディングス', 
    'のむらふどうさんほーるでぃんぐす', 
    'https://www.nomura-re-hd.co.jp/', 
    '東京都新宿区西新宿1丁目26-2', 
    'nomura-re-hd.png' 
),
(
    NULL, 
    '株式会社野村総合研究所', 
    'のむらそうごうけんきゅうじょ', 
    'https://www.nri.com/jp/', 
    '東京都千代田区大手町1-9-2 大手町フィナンシャルシティ グランキューブ', 
    'nri.png' 
),
(
    NULL, 
    '株式会社ノジマ', 
    'のじま', 
    'https://www.nojima.co.jp/', 
    '神奈川県横浜市西区南幸１丁目１番１号JR横浜タワー 26階', 
    'nojima.png' 
),
(
    NULL, 
    'ノボ ノルディスク ファーマ株式会社', 
    'のぼのるでぃすくふぁーま', 
    'https://www.novonordisk.co.jp/', 
    '東京都千代田区丸の内2-1-1明治安田生命ビル', 
    'novonordisk.png' 
),
(
    NULL, 
    '株式会社ノーリツ', 
    'のーりつ', 
    'https://www.noritz.co.jp/', 
    '神戸市中央区江戸町93番', 
    'noritz.png' 
),
(
    NULL, 
    'パナソニック株式会社', 
    'ぱなそにっく', 
    'https://www.panasonic.com/jp/about.html', 
    '東京都港区東新橋1-5-1 パナソニック東京汐留ビル', 
    'panasonic.png' 
),
(
    NULL, 
    '花王株式会社', 
    'かおう', 
    'https://www.kao.com/jp/', 
    '東京都中央区日本橋茅場町一丁目14番10号', 
    'kao.png' 
),
(
    NULL, 
    'ハウス食品株式会社', 
    'はうすしょくひん', 
    'https://housefoods.jp/', 
    '東京都千代田区紀尾井町6番3号', 
    'housefoods.png' 
),
(
    NULL, 
    '浜松ホトニクス', 
    'はままつほとにくす', 
    'https://www.hamamatsu.com/jp/ja.html', 
    '静岡県浜松市中央区砂山町325-6 日本生命浜松駅前ビル', 
    'hamamatsu.png' 
),
(
    NULL, 
    '株式会社博報堂ＤＹホールディングス', 
    'はくほうどうでぃわいほーるでぃんぐす', 
    'https://www.hakuhodody-holdings.co.jp/', 
    '東京都港区赤坂5丁目3番1号 赤坂Bizタワー', 
    'hakuhodody-holdings.png' 
),
(
    NULL, 
    '株式会社ファンケル', 
    'ふぁんける', 
    'https://www.fancl.jp/index.html', 
    '横浜市中区山下町89-1', 
    'fancl.png' 
),
(
    NULL, 
    '阪急電鉄株式会社', 
    'はんきゅうでんてつ', 
    'https://www.hankyu.co.jp/?link=hamburger', 
    '大阪市北区芝田一丁目16番1号', 
    'hankyu.png' 
),
(
    NULL, 
    '八千代工業株式会社', 
    'やちよこうぎょう', 
    'https://www.yachiyo-ind.co.jp/', 
    '埼玉県狭山市柏原393番地', 
    'yachiyo.png' 
),
(
    NULL, 
    '株式会社パソナ ', 
    'ぱそな', 
    'https://www.pasona.co.jp/', 
    '東京都港区南青山3-1-30', 
    'pasona.png' 
),
(
    NULL, 
    '株式会社日立製作所', 
    'ひたちせいてつじょ', 
    'https://www.hitachi.co.jp/', 
    '東京都千代田区丸の内一丁目6番6号', 
    'hitach.png' 
),
(
    NULL, 
    '日産自動車株式会社', 
    'にっさんじどうしゃ', 
    'https://nissan.co.jp/', 
    '神奈川県横浜市西区高島一丁目1番1号', 
    'nissan.png' 
),
(
    NULL, 
    '株式会社ひらまつ', 
    'ひらまつ', 
    'https://www.hiramatsu.co.jp/', 
    '東京都渋谷区恵比寿 4-17-3', 
    'hiramatsu.png' 
),
(
    NULL, 
    '日立建機株式会社', 
    'ひたちけんき', 
    'https://www.hitachicm.com/global/ja/', 
    '東京都台東区東上野二丁目16番1号', 
    'hitachicm.png' 
),
(
    NULL, 
    '日野自動車株式会社', 
    'ひのじどうしゃ', 
    'https://www.hino.co.jp/', 
    '東京都日野市日野台3丁目1番地1', 
    'hino.png' 
),
(
    NULL, 
    'ヒューリック株式会社', 
    'ひゅーりっく', 
    'https://www.hulic.co.jp/', 
    '東京都中央区日本橋大伝馬町7番3号', 
    'hulic.png' 
),
(
    NULL, 
    '株式会社肥後銀行', 
    'ひごぎんこう', 
    'https://www.higobank.co.jp/', 
    '熊本市中央区練兵町1番地', 
    'higobank.png' 
),
(
    NULL, 
    'ヒラキ株式会社', 
    'ひらき', 
    'https://company.hiraki.co.jp/', 
    '神戸市西区岩岡町野中字福吉556', 
    'hiraki.png' 
),
(
    NULL, 
    '株式会社日比谷花壇', 
    'ひびやかだん', 
    'https://www.hibiya.co.jp/', 
    '東京都港区南麻布1-6-30', 
    'hibiya.png' 
),
(
    NULL, 
    '富士通株式会社', 
    'ふじつう', 
    'https://global.fujitsu/ja-jp', 
    '神奈川県川崎市中原区上小田中4-1-1', 
    'fujitsu.png' 
),
(
    NULL, 
    '富士フイルムホールディングス株式会社', 
    'ふじふぃるむほーるでぃんぐす', 
    'https://holdings.fujifilm.com/ja', 
    '東京都港区赤坂9丁目7番3号', 
    'fujifilm.png' 
),
(
    NULL, 
    '富士電機株式会社', 
    'ふじでんき', 
    'https://www.fujielectric.co.jp/index.html', 
    '東京都品川区大崎一丁目11番2号ゲートシティ大崎イーストタワー', 
    'fujielectric.png' 
),
(
    NULL, 
    '古河電気工業株式会社', 
    'ふるかわでんきこうぎょう', 
    'https://www.furukawa.co.jp/', 
    '東京都千代田区大手町2丁目6番4号', 
    'furukawa.png' 
),
(
    NULL, 
    '扶桑化学工業株式会社', 
    'ふそうかがくこうぎょう', 
    'https://fusokk.co.jp/', 
    '大阪府大阪市中央区北浜三丁目5番29号', 
    'fusokk.png' 
),
(
    NULL, 
    '株式会社不二家', 
    'ふじや', 
    'https://www.fujiya-peko.co.jp/', 
    '東京都文京区大塚2-15-6', 
    'fujiya.png' 
),
(
    NULL, 
    '株式会社富士薬品', 
    'ふじやくひん', 
    'https://www.fujiyakuhin.co.jp/', 
    '埼玉県さいたま市大宮区桜木町4丁目383番地', 
    'fujiyakuhin.png' 
),
(
    NULL, 
    '株式会社不動テトラ', 
    'ふどうてとら', 
    'https://www.fudotetra.co.jp/', 
    '東京都中央区日本橋小網町7番2号 ぺんてるビル', 
    'fudotetra.png' 
),
(
    NULL, 
    'フジテック株式会社', 
    'ふじてっく', 
    'https://www.fujitec.co.jp/', 
    'フジテック株式会社', 
    'fujitec.png' 
),
(
    NULL, 
    'ヘリオス テクノ ホールディング株式会社', 
    'へりおすてくのほーるでぃんぐす', 
    'https://www.heliostec-hd.co.jp/', 
    '東京都中央区日本橋馬喰町1-11-10', 
    'heliostec.png' 
),
(
    NULL, 
    '株式会社ヘキサドライブ', 
    'へきさどらいぶ', 
    'https://hexadrive.jp/', 
    '大阪市浪速区難波中2-10-70パークスタワー28F', 
    'hexadrive.png' 
),
(
    NULL, 
    '株式会社ヘルシーピット', 
    'へるしーぴっと', 
    'https://www.healthypit.co.jp/', 
    '東京都世田谷区成城2-40-5 ヴェルドミール成城303・304', 
    'healthypit.png' 
),
(
    NULL, 
    '株式会社ヘルスケアシステムズ', 
    'へるすけあしすてむず', 
    'https://hc-sys.com/', 
    '愛知県名古屋市昭和区白金一丁目14番18号', 
    'hc-sys.png' 
),
(
    NULL, 
    '株式会社ヘリオス', 
    'へりおす', 
    'https://www.healios.co.jp/', 
    '東京都千代田区有楽町１丁目１番２号 日比谷三井タワー１２階', 
    'healios.png' 
),
(
    NULL, 
    '株式会社ヘッドウォータース', 
    'へっどうぉーたーす', 
    'https://www.headwaters.co.jp/', 
    '東京都新宿区西新宿6-5-1新宿アイランドタワー4階', 
    'headwaters.png' 
),
(
    NULL, 
    'ヘラマンタイトン株式会社', 
    'へらまんたいとん', 
    'https://www.hellermanntyton.co.jp/index.html', 
    '東京都渋谷区笹塚1-48-3  住友不動産笹塚太陽ビル6F', 
    'hellermanntyton.png' 
),
(
    NULL, 
    '本田技研工業株式会社', 
    'ほんだぎけんこうぎょう', 
    'https://www.honda.co.jp/', 
    '東京都港区南青山2-1-1', 
    'honda.png' 
),
(
    NULL, 
    '保土谷化学工業株式会社', 
    'ほどがやかがくこうぎょう', 
    'https://www.hodogaya.co.jp/', 
    '東京都港区東新橋一丁目9番2号汐留住友ビル', 
    'hodogaya.png' 
),
(
    NULL, 
    '北越コーポレーション株式会社', 
    'ほくえつこーぽれーしょん', 
    'https://hokuetsucorp.com/', 
    '東京都中央区日本橋本石町3-2-2', 
    'hokuetsucorp.png' 
),
(
    NULL, 
    '株式会社堀場製作所', 
    'ほりばせいてつじょ', 
    'https://www.horiba.com/jpn/', 
    '京都市南区吉祥院宮の東町2番地', 
    'horiba.png' 
),
(
    NULL, 
    'ホソカワミクロン株式会社', 
    'ほそかわみくろん', 
    'https://www.hosokawamicron.co.jp/jp/', 
    '大阪府枚方市招提田近1丁目9番地', 
    'hosokawamicron.png' 
),
(
    NULL, 
    '株式会社ホンダアクセス', 
    'ほんだあくせす', 
    'https://www.honda.co.jp/ACCESS/', 
    '埼玉県新座市野火止8-18-4', 
    'hondaas.png' 
),
(
    NULL, 
    '本間ゴルフ', 
    'ほんま', 
    'https://www.honmagolf.com/jp', 
    '東京都港区六本木6-10-1六本木ヒルズ森タワー35階', 
    'honmagolf.png' 
),
(
    NULL, 
    'ホーチキ株式会社', 
    'ほーちき', 
    'https://www.hochiki.co.jp/', 
    '東京都品川区上大崎二丁目10番43号', 
    'hochiki.png' 
),
(
    NULL, 
    '北陸電力株式会社', 
    'ほくりくでんりょく', 
    'https://www.rikuden.co.jp/', 
    '富山県富山市牛島町１５番１号', 
    'rikuden.png' 
),
(
    NULL, 
    'マツダ株式会社', 
    'まつだ', 
    'https://www.mazda.com/ja/', 
    '広島県安芸郡府中町新地3番1号', 
    'mazda.png' 
),
(
    NULL, 
    'マルハニチロ株式会社', 
    'まるはにちろ', 
    'https://www.maruha-nichiro.co.jp/', 
    '東京都江東区豊洲三丁目2番20号 豊洲フロント', 
    'maruha-nichiro.png' 
),
(
    NULL, 
    '丸紅株式会社', 
    'まるべに', 
    'https://www.marubeni.com/jp/', 
    '東京都千代田区大手町一丁目4番2号', 
    'marubeni.png' 
),
(
    NULL, 
    '丸善石油化学株式会社', 
    'まるぜんせきゆかがく', 
    'https://www.chemiway.co.jp/', 
    '東京都中央区入船二丁目1番1号 ', 
    'chemiway.png' 
),
(
    NULL, 
    'マニー株式会社', 
    'まにー', 
    'https://www.mani.co.jp/', 
    '栃木県宇都宮市清原工業団地8番3', 
    'mani.png' 
),
(
    NULL, 
    '株式会社マクロミル', 
    'まくろみる', 
    'https://www.macromill.com/', 
    '東京都港区港南2-16-1 品川イーストワンタワー 11F', 
    'macromill.png' 
),
(
    NULL, 
    'マルマン株式会社', 
    'まるまん', 
    'https://www.e-maruman.co.jp/', 
    '東京都中野区中央2-36-12 ', 
    'maruman.png' 
),
(
    NULL, 
    '三菱電機株式会社', 
    'みつびしでんき', 
    'https://www.mitsubishielectric.co.jp/', 
    '東京都千代田区丸の内2-7-3 東京ビル', 
    'mitsubishielectric.png' 
),
(
    NULL, 
    '株式会社三井住友銀行', 
    'みついすみともぎんこう', 
    'https://www.smbc.co.jp/', 
    '東京都千代田区丸の内一丁目1番2号', 
    'smbc.png' 
),
(
    NULL, 
    '株式会社Mizkan', 
    'みつかん', 
    'https://www.mizkan.co.jp/company/', 
    '愛知県半田市中村町 2-6', 
    'mizkan.png' 
),
(
    NULL, 
    '株式会社みずほフィナンシャルグループ ', 
    'みずほふぃなんしゃるぐるーぷ', 
    'https://www.mizuho-fg.co.jp/index.html', 
    '東京都千代田区大手町1丁目5番5号', 
    'mizuho-fg.png' 
),
(
    NULL, 
    'ミツミ電機株式会社', 
    'みつみでんき', 
    'https://www.mitsumi.co.jp/', 
    '東京都多摩市鶴牧2-11-2', 
    'mitsumi.png' 
),
(
    NULL, 
    'ミサワホーム株式会社', 
    'みさわほーむ', 
    'https://www.misawa.co.jp/', 
    '東京都新宿区西新宿二丁目4番1号新宿NSビル', 
    'misawa.png' 
),
(
    NULL, 
    'ミネベアミツミ株式会社', 
    'みねべあみつみ', 
    'https://minebeamitsumi.com/', 
    '長野県北佐久郡御代田町大字御代田4106-73', 
    'minebeamitsumi.png' 
),
(
    NULL, 
    '三井化学株式会社', 
    'みついかがく', 
    'https://jp.mitsuichemicals.com/jp/index.htm', 
    '東京都中央区八重洲2-2-1東京ミッドタウン八重洲 八重洲セントラルタワー', 
    'mitsuichemicals.png' 
),
(
    NULL, 
    '三井物産株式会社', 
    'みついぶっさん', 
    'https://www.mitsui.com/jp/ja/', 
    '東京都千代田区大手町一丁目2番1号', 
    'mitsui.png' 
),
(
    NULL, 
    'ミドリ安全株式会社', 
    'みどりあんぜん', 
    'https://www.midori-anzen.co.jp/ja/', 
    '東京都渋谷区広尾5丁目4番3号', 
    'midori-anzen.png' 
),
(
    NULL, 
    '株式会社良品計画', 
    'りょうひんけいかく', 
    'https://www.ryohin-keikaku.jp/', 
    '東京都文京区後楽2-5-1 住友不動産飯田橋ファーストビル', 
    'ryohin-keikaku.png' 
),
(
    NULL, 
    '株式会社武蔵野', 
    'むさしの', 
    'https://www.ms-net.co.jp/', 
    '埼玉県朝霞市西原1-1-1 武蔵野ビル', 
    'ms-net.png' 
),
(
    NULL, 
    'むつみ建設株式会社', 
    'むつみけんせつ', 
    'http://www.mutsumi-ken.co.jp/', 
    '秋田県潟上市天王字北野256番地', 
    'mutsumi-ken.png' 
),
(
    NULL, 
    '株式会社メルカリ', 
    'めるかり', 
    'https://about.mercari.com/', 
    '東京都港区六本木6-10-1六本木ヒルズ森タワー', 
    'mercari.png' 
),
(
    NULL, 
    '株式会社メディアドゥ', 
    'めでぃあどぅ', 
    'https://mediado.jp/', 
    '東京都千代田区一ツ橋1-1-1パレスサイドビル 5F・8F', 
    'mediado.png' 
),
(
    NULL, 
    '株式会社メイテック', 
    'めいてっく', 
    'https://www.meitec.co.jp/', 
    '東京都台東区上野1丁目1-10 オリックス上野1丁目ビル', 
    'meitec.png' 
),
(
    NULL, 
    '株式会社メガチップス', 
    'めがちっぷす', 
    'https://www.megachips.co.jp/', 
    '大阪市淀川区宮原1丁目1番1号 新大阪阪急ビル', 
    'megachips.png' 
),
(
    NULL, 
    '株式会社メディカルシステムネットワーク', 
    'めでぃかるしすてむねっとわーく', 
    'https://www.msnw.co.jp/', 
    '札幌市中央区北10条西24丁目3番地 AKKビル', 
    'msnw.png' 
),
(
    NULL, 
    'メルセデス・ベンツ日本合同会社', 
    'めるせです・べんつにほんごうどう', 
    'https://www.mercedes-benz.co.jp/', 
    '千葉県千葉市美浜区中瀬2丁目6番地1 ワールドビジネスガーデン マリブウエスト ', 
    'mercedes-benz.png' 
),
(
    NULL, 
    '株式会社メディパルホールディングス', 
    'めでぃぱるほーるでぃんぐす', 
    'https://www.medipal.co.jp/', 
    '東京都中央区京橋三丁目1番1号', 
    'medipal.png' 
),
(
    NULL, 
    '株式会社メイコー', 
    'めいこー', 
    'https://www.meiko-elec.com/', 
    '神奈川県綾瀬市大上5-14-15', 
    'meiko.png' 
),
(
    NULL, 
    '株式会社メニコン', 
    'めにこん', 
    'https://www.menicon.co.jp/', 
    '愛知県名古屋市中区葵三丁目21番19号', 
    'menicon.png' 
),
(
    NULL, 
    'メトロエンジン株式会社', 
    'めとろえんじん', 
    'https://info.metroengines.jp/', 
    '東京都品川区西五反田七丁目25番5号 西五反田七丁目ビル9階', 
    'metroengines.png' 
),
(
    NULL, 
    '株式会社モリサワ', 
    'もりさわ', 
    'https://www.morisawa.co.jp/', 
    '大阪市浪速区敷津東2-6-25', 
    'morisawa.png' 
),
(
    NULL, 
    '株式会社モスフードサービス', 
    'もすふーどさーびす', 
    'https://www.mos.co.jp/company/', 
    '東京都品川区大崎2-1-1 ThinkPark Tower 4階', 
    'mos.png' 
),
(
    NULL, 
    '株式会社モリタホールディングス', 
    'もりたほーるでぃんぐす', 
    'https://www.morita119.com/', 
    '大阪市中央区道修町3丁目6番1号 京阪神御堂筋ビル12階', 
    'morita.png' 
),
(
    NULL, 
    '株式会社モルフォ', 
    'もるふぉ', 
    'https://www.morphoinc.com/', 
    '東京都千代田区神田錦町 2-2-1 KANDA SQUARE11階', 
    'morphoinc.png' 
),
(
    NULL, 
    '株式会社MonotaRO', 
    'ものたろう', 
    'https://corp.monotaro.com/', 
    '大阪市北区梅田三丁目2番2号 JPタワー大阪22階', 
    'monotaro.png' 
),
(
    NULL, 
    'モリト株式会社', 
    'もりと', 
    'https://www.morito.co.jp/', 
    '大阪府大阪市中央区南本町4-2-4', 
    'morito.png' 
),
(
    NULL, 
    'ヤマハ株式会社', 
    'やまは', 
    'https://www.yamaha.com/ja/', 
    '静岡県浜松市中央区中沢町10番1号', 
    'yamaha.png' 
),
(
    NULL, 
    'ヤマト運輸株式会社', 
    'やまとうんそう', 
    'https://www.kuronekoyamato.co.jp/', 
    '東京都中央区銀座2-16-10', 
    'kuronekoyamato.png' 
),
(
    NULL, 
    '株式会社ヤクルト本社', 
    'やくると', 
    'https://www.yakult.co.jp/', 
    '東京都港区海岸1丁目10番30号', 
    'yakult.png' 
),
(
    NULL, 
    'ヤマトホールディングス株式会社', 
    'やまとほーるでぃんぐす', 
    'https://www.yamato-hd.co.jp/', 
    '東京都中央区銀座2-16-10', 
    'yamato-hd.png' 
),
(
    NULL, 
    '株式会社ヤマダホールディングス', 
    'やまだほーるでぃんぐす', 
    'https://www.yamada-holdings.jp/', 
    '群馬県高崎市栄町1番1号', 
    'yamada-holdings.png' 
),
(
    NULL, 
    'ヤマハ発動機株式会社', 
    'やまははつどうき', 
    'https://global.yamaha-motor.com/jp/', 
    '静岡県磐田市新貝2500', 
    'yamaha-motor.png' 
),
(
    NULL, 
    'ヤマウチ株式会社', 
    'やまうち', 
    'https://yamauchi.co.jp/', 
    '大阪府枚方市招提田近2-7', 
    'yamauchi.png' 
),
(
    NULL, 
    '株式会社ヤマニパッケージ', 
    'やまにぱっけーじ', 
    'https://yamani-p.com/', 
    '岐阜県岐阜市清本町2丁目44番地', 
    'yamani-p.png' 
),
(
    NULL, 
    'ユニ・チャーム株式会社', 
    'ゆに・ちゃーむ', 
    'https://www.unicharm.co.jp/ja/home.html', 
    '愛媛県四国中央市金生町下分182番地', 
    'unicharm.png' 
),
(
    NULL, 
    '株式会社ユニクロ ', 
    'ゆにくろ', 
    'https://www.uniqlo.com/jp/ja/', 
    '山口県山口市佐山10717番地1', 
    'uniqlo.png' 
),
(
    NULL, 
    'ユニデンホールディングス株式会社', 
    'ゆにでんほーるでぃんぐす', 
    'https://unidenholdings.jp/', 
    '東京都中央区日本橋室町2-3-1', 
    'unidenholdings.png' 
),
(
    NULL, 
    'ユアサ商事株式会社 ', 
    'ゆあさしょうじ', 
    'https://www.yuasa.co.jp/', 
    '東京都千代田区神田美土代町7番地', 
    'yuasa.png' 
),
(
    NULL, 
    '株式会社ユー・エス・エス', 
    'ゆー・えす・えす', 
    'https://www.ussnet.co.jp/', 
    '愛知県東海市新宝町507番地の20', 
    'ussnet.png' 
),
(
    NULL, 
    'ユナイテッド株式会社', 
    'ゆないてっど', 
    'https://united.jp/', 
    '東京都渋谷区渋谷1-2-5 MFPR渋谷ビル B1F', 
    'united.png' 
),
(
    NULL, 
    '株式会社ユニバーサルエンターテインメント', 
    'ゆにばーさるえんたーていめんと', 
    'https://www.universal-777.com/', 
    '東京都江東区有明三丁目7番26号 有明フロンティアビル A棟', 
    'universal.png' 
),
(
    NULL, 
    '株式会社ユナイテッドアローズ', 
    'ゆないてっどあろーず', 
    'https://www.united-arrows.co.jp/', 
    '東京都渋谷区神宮前三丁目28番1号', 
    'united-arrows.png' 
),
(
    NULL, 
    'ユニシステム株式会社', 
    'ゆにしすてむ', 
    'https://www.unisystem.co.jp/', 
    '東京都豊島区目白2-16-20 TCS-HD南池袋ビル', 
    'unisystem.png' 
),
(
    NULL, 
    'ヨネックス株式会社', 
    'よねっくす', 
    'https://www.yonex.co.jp/', 
    '東京都文京区湯島3-23-13', 
    'yonex.png' 
),
(
    NULL, 
    '株式会社ヨコハマタイヤジャパン', 
    'よこはまたいやじゃぱん', 
    'https://www.y-yokohama.com/group/ytj/', 
    '東京都港区港南2-15-3 品川インターシティC棟13階', 
    'y-yokohama.png' 
),
(
    NULL, 
    '株式会社ヨドバシカメラ', 
    'よどばしかめら', 
    'https://www.yodobashi.co.jp/company/', 
    '東京都新宿区新宿5-3-1', 
    'yodobashi.png' 
),
(
    NULL, 
    '株式会社ヨネクラ', 
    'よねくら', 
    'https://www.yonekura-saga.co.jp/', 
    '佐賀県鹿島市中村1618-7', 
    'yonekura-saga.png' 
),
(
    NULL, 
    '株式会社ヨシックスホールディングス', 
    'よしっくすほーるでぃんぐす', 
    'https://yossix.co.jp/', 
    '愛知県名古屋市東区徳川1-9-30', 
    'yossix.png' 
),
(
    NULL, 
    'ヨシケイ開発株式会社', 
    'よしけいかいはつ', 
    'https://corporate.yoshikei-dvlp.co.jp/', 
    '静岡県静岡市駿河区国吉田1丁目8-30', 
    'yoshikei-dvlp.png' 
),
(
    NULL, 
    '株式会社ヨシムラジャパン', 
    'よしむらじゃぱん', 
    'https://www.yoshimura-jp.com/', 
    '神奈川県愛甲郡愛川町中津6748', 
    'yoshimura-jp.png' 
),
(
    NULL, 
    'ライオン株式会社', 
    'らいおん', 
    'https://www.lion.co.jp/ja/', 
    '東京都台東区蔵前1-3-28', 
    'lion.png' 
),
(
    NULL, 
    '株式会社ライフコーポレーション', 
    'らいふこーぽれーしょん', 
    'http://www.lifecorp.jp/', 
    '大阪市淀川区西宮原2-2-22', 
    'lifecorp.png' 
),
(
    NULL, 
    '株式会社ラウンドワンジャパン', 
    'らうんどわんじゃぱん', 
    'https://www.round1-group.co.jp/', 
    '大阪府大阪市中央区難波5丁目1番60号 なんばスカイオ23F', 
    'round1-group.png' 
),
(
    NULL, 
    '株式会社ラストワンマイル', 
    'らすとわんまいる', 
    'https://lomgrp.co.jp/', 
    '東京都豊島区東池袋4丁目21-1アウルタワー3F・4F', 
    'lomgrp.png' 
),
(
    NULL, 
    '株式会社ラック', 
    'らっく', 
    'https://www.lac.co.jp/', 
    '東京都千代田区平河町2丁目16番1号 平河町森タワー', 
    'lac.png' 
),
(
    NULL, 
    '株式会社ラピーヌ', 
    'らぴーぬ', 
    'https://www.lapine.co.jp/', 
    '東京都千代田区神田東松下町17番地', 
    'lapine.png' 
),
(
    NULL, 
    'ラディックス株式会社', 
    'らでぃっくす', 
    'https://www.radix.ad.jp/', 
    '東京都渋谷区桜丘町1-2 渋谷サクラステージセントラルビル16階', 
    'radix.png' 
),
(
    NULL, 
    '株式会社リクルートホールディングス', 
    'りくるーとほーるでぃんぐす', 
    'https://recruit-holdings.com/ja/', 
    '東京都千代田区丸の内1丁目9番2号', 
    'recruit-holdings.png' 
),
(
    NULL, 
    '株式会社リコー', 
    'りこー', 
    'https://jp.ricoh.com/', 
    '東京都大田区中馬込1-3-6', 
    'ricoh.png' 
),
(
    NULL, 
    'リンナイ株式会社', 
    'りんない', 
    'https://www.rinnai.co.jp/', 
    '愛知県名古屋市中川区福住町2番26号', 
    'rinnai.png' 
),
(
    NULL, 
    '株式会社リブセンス', 
    'りぶせんす', 
    'https://www.livesense.co.jp/', 
    '東京都港区海岸1-7-1 東京ポートシティ竹芝10階', 
    'livesense.png' 
),
(
    NULL, 
    '株式会社リンクアンドモチベーション', 
    'りんくあんどもちべーしょん', 
    'https://www.lmi.ne.jp/', 
    '東京都中央区銀座4丁目12-15 歌舞伎座タワー15階', 
    'lmi.png' 
),
(
    NULL, 
    '株式会社リミックスポイント', 
    'りみっくすぽいんと', 
    'https://www.remixpoint.co.jp/', 
    '東京都港区虎ノ門４丁目３番９号 住友新虎ノ門ビル', 
    'remixpoint.png' 
),
(
    NULL, 
    '株式会社リンガーハット', 
    'りんがーはっと', 
    'https://www.ringerhut.co.jp/', 
    '長崎県長崎市鍛冶屋町6-50', 
    'ringerhut.png' 
),
(
    NULL, 
    'リソルホールディングス株式会社 ', 
    'りそるほーるでぃんぐす', 
    'https://www.resol.jp/', 
    '東京都新宿区西新宿6-24-1', 
    'resol.png' 
),
(
    NULL, 
    '株式会社リバネス', 
    'りばねす', 
    'https://lne.st/', 
    '東京都新宿区下宮比町1-4 飯田橋御幸ビル', 
    'lne.png' 
),
(
    NULL, 
    'ルネサス エレクトロニクス株式会社', 
    'るねさすえれくとろにくす', 
    'https://www.renesas.com/jp/ja', 
    '東京都江東区豊洲三丁目2番24号', 
    'renesas.png' 
),
(
    NULL, 
    'ルートインジャパン株式会社 ', 
    'るーといんじゃぱん', 
    'https://www.route-inn.co.jp/', 
    '東京都品川区大井1-35-3 ', 
    'route-inn.png' 
),
(
    NULL, 
    '株式会社ルミネ', 
    'るみね', 
    'https://www.lumine.co.jp/', 
    '東京都渋谷区代々木2-2-2 JR東日本本社ビル10F', 
    'lumine.png' 
),
(
    NULL, 
    'ルーシッド株式会社', 
    'るーしっど', 
    'https://lucidsoft.jp/', 
    '東京都渋谷区千駄ヶ谷3丁目52-1 クロスサイドビル5F', 
    'lucidsoft.png' 
),
(
    NULL, 
    '株式会社ルネサンス', 
    'るねさんす', 
    'https://www.s-renaissance.co.jp/', 
    '東京都墨田区両国2-10-14 両国シティコア3階', 
    's-renaissance.png' 
),
(
    NULL, 
    '株式会社ルシアン', 
    'るしあん', 
    'https://www.lecien.co.jp/', 
    '京都市南区吉祥院中島町29番地', 
    'lecien.png' 
),
(
    NULL, 
    '株式会社レオパレス21', 
    'れおぱれす', 
    'https://www.leopalace21.co.jp/', 
    '東京都中野区本町2丁目54番11号', 
    'leopalace21.png' 
),
(
    NULL, 
    '株式会社レッグス', 
    'れっぐす', 
    'https://www.legs.co.jp/', 
    '東京都港区南青山二丁目26番1号 D-LIFEPLACE南青山11・12階', 
    'legs.png' 
),
(
    NULL, 
    'レカム株式会', 
    'れかむ', 
    'https://www.recomm.co.jp/', 
    '東京都渋谷区代々木三丁目２５番３号 あいおいニッセイ同和損保新宿ビル１２階', 
    'recomm.png' 
),
(
    NULL, 
    'レッドホースコーポレーション株式会社', 
    'れっどほーすこーぽれーしょん', 
    'https://www.redhorse.co.jp/', 
    '東京都墨田区横網1-10-5 KOKUGIKAN FRONT BUILDING 2階', 
    'redhorse.png' 
),
(
    NULL, 
    '株式会社レアジョブ', 
    'れあじょぶ', 
    'https://www.rarejob.co.jp/', 
    '東京都渋谷区神宮前6-27-8 京セラ原宿ビル2階', 
    'rarejob.png' 
),
(
    NULL, 
    '株式会社レアゾン・ホールディングス', 
    'れあぞん・ほーるでぃんぐす', 
    'https://reazon.jp/', 
    '東京都新宿区四谷1-6-1 YOTSUYA TOWER内', 
    'reazon.png' 
),
(
    NULL, 
    '株式会社ローソン', 
    'ろーそん', 
    'https://www.lawson.co.jp/company/index.html', 
    '東京都品川区大崎一丁目11番2号 ゲートシティ大崎イーストタワー', 
    'lawson.png' 
),
(
    NULL, 
    '株式会社ロッテ', 
    'ろって', 
    'https://www.lotte.co.jp/', 
    '東京都新宿区西新宿3-20-1', 
    'lotte.png' 
),
(
    NULL, 
    'ローランド株式会社', 
    'ろーらんど', 
    'https://www.roland.com/jp/', 
    '静岡県浜松市浜名区細江町中川2036-1', 
    'roland.png' 
),
(
    NULL, 
    'ロイヤルホールディングス株式会社', 
    'ろいやるほーるでぃんぐす', 
    'https://www.royal-holdings.co.jp/', 
    '東京都世田谷区桜新町一丁目34番6号', 
    'royal-holdings.png' 
),
(
    NULL, 
    'ローム株式会社', 
    'ろーむ', 
    'https://www.rohm.co.jp/', 
    '京都市右京区西院溝崎町21', 
    'rohm.png' 
),
(
    NULL, 
    'ローランド ディー.ジー.株式会社', 
    'ろーらんどでぃーじー', 
    'https://www.rolanddg.com/', 
    '静岡県浜松市浜名区新都田一丁目1番2号', 
    'rolanddg.png' 
),
(
    NULL, 
    '株式会社ロイヤルホテル', 
    'ろいやるほてる', 
    'http://www.royalhotel.jpn.com/', 
    '大阪市北区中之島5丁目3番68号', 
    'royalhotel.png' 
),
(
    NULL, 
    '株式会社ロッソ', 
    'ろっそ', 
    'https://www.rosso.co.jp/', 
    '東京都八王子市小宮町841-1', 
    'rosso.png' 
),
(
    NULL, 
    'ロジザード株式会社', 
    'ろじざーど', 
    'https://www.logizard.co.jp/', 
    '東京都中央区日本橋人形町三丁目3番6号', 
    'logizard.png' 
),
(
    NULL, 
    'ワタミ株式会社', 
    'わたみ', 
    'https://www.watami.co.jp/', 
    '東京都大田区羽田一丁目1番3号', 
    'watami.png' 
),
(
    NULL, 
    '株式会社ワコール', 
    'わこーる', 
    'https://www.wacoalholdings.jp/', 
    '京都府京都市南区吉祥院中島町29 ', 
    'wacoalholdings.png' 
),
(
    NULL, 
    '株式会社ワークマン', 
    'わーくまん', 
    'https://www.workman.co.jp/', 
    '東京都台東区東上野4-8-1 TIXTOWER UENO 11F', 
    'workman.png' 
),
(
    NULL, 
    'ワタベウェディング株式会社', 
    'わたべうぇでぃんぐ', 
    'https://www.watabe-wedding.co.jp/', 
    '京都市上京区烏丸通丸太町上る春日町427-3', 
    'watabe-wedding.png' 
),
(
    NULL, 
    '株式会社ワーナーミュージック・ジャパン', 
    'わーなーみゅーじっく', 
    'https://wmg.jp/', 
    '東京都港区六本木１丁目４番５号', 
    'wmg.png' 
),
(
    NULL, 
    '株式会社ワールドホールディングス ', 
    'わーるどほーるでぃんぐす', 
    'https://world-hd.co.jp/', 
    '福岡県福岡市博多区博多駅前2-1-1 福岡朝日ビル6Ｆ', 
    'world-hd.png' 
),
(
    NULL, 
    '株式会社ワイズテーブルコーポレーション', 
    'わいずてーぶるこーぽれーしょん', 
    'https://www.ystable.co.jp/', 
    '東京都港区赤坂8丁目10番22号', 
    'ystable.png' 
),
(
    NULL, 
    '株式会社ワコム', 
    'わこむ', 
    'https://www.wacom.com/ja-jp/home.aspx', 
    '埼玉県加須市豊野台2-510-1', 
    'wacom.com.png' 
);

